#!/usr/bin/env node
/*
  Catalog: reads every style's metadata, default params and retention beats (by building it in headless Chrome)
  and writes the generated parts of the docs.

  node tools/catalog.mjs              refresh every style README block + styles/README.md + docs/NICHE-MAP.md
  node tools/catalog.mjs <id> [...]   refresh only these styles' README blocks (safe while others edit theirs)
  node tools/catalog.mjs --json       print the raw catalog as JSON

  A style README keeps its hand-written sections; only the text between
  "<!-- catalog:start" and "<!-- catalog:end -->" is replaced.
*/
import puppeteer from 'puppeteer-core';
import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { ROOT, chromePath, CHROME_ARGS, listStyles, writeDevPage, parseArgs, readJSON, pretty } from './lib.mjs';

const { flags, pos } = parseArgs(process.argv.slice(2));
const all = listStyles();
for (const id of pos) if (!all.includes(id)) throw new Error(`unknown style ${id}`);

async function readCatalog(ids) {
  const reel = { name: 'catalog', slug: `catalog-${process.pid}`, sequence: ids.map((id) => ({ key: id, style: id, params: {} })) };
  const devPage = writeDevPage(reel), url = pathToFileURL(devPage).href + '?render=1';
  const browser = await puppeteer.launch({ executablePath: chromePath(), headless: true, args: CHROME_ARGS });
  try {
    const page = await browser.newPage();
    const errs = [];
    page.on('pageerror', (e) => errs.push(String(e.message || e)));
    page.on('console', (m) => { if (m.type() === 'error') errs.push(m.text()); });
    await page.goto(url, { waitUntil: 'networkidle0', timeout: 120000 });
    await page.waitForFunction('window.__rl && window.Reel', { timeout: 60000 });
    await page.evaluate(() => window.__rl.init());
    const cat = await page.evaluate(() => window.__rl.catalog());
    if (errs.length) console.log('page messages:\n  ' + [...new Set(errs)].join('\n  '));
    return cat;
  } finally { await browser.close(); fs.rmSync(devPage, { force: true }); }
}

const examplesOf = (id) => {
  const dir = path.join(ROOT, 'styles', id, 'examples');
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir).filter((f) => f.endsWith('.json')).sort().map((f) => {
    const j = readJSON(path.join(dir, f)), base = f.replace(/\.json$/, '');
    return { file: `examples/${f}`, name: base, meta: j.meta || {}, jpg: fs.existsSync(path.join(dir, base + '.jpg')) ? `examples/${base}.jpg` : null };
  });
};
const md = (s) => String(s ?? '').replace(/\|/g, '\\|');
const list = (a) => (a && a.length ? a.join(' · ') : '—');

function block(c) {
  const ex = examplesOf(c.id);
  const L = [];
  L.push('<!-- catalog:start · generated by tools/catalog.mjs from style.js; edit the style, then rerun -->');
  L.push('| | |', '|---|---|');
  L.push(`| **Style id** | \`${c.id}\` |`);
  L.push(`| **Primary niches** | ${md(list(c.niches && c.niches.primary))} |`);
  L.push(`| **Also fits** | ${md(list(c.niches && c.niches.similar))} |`);
  L.push(`| **Length** | ${c.duration.toFixed(1)} s · poster frame ${c.poster ?? '—'} s · ${c.cues} sound cues |`);
  L.push(`| **Palette** | ${(c.palette || []).map((h) => `\`${h}\``).join(' ')} |`);
  L.push(`| **Techniques** | ${md(list(c.meta.techniques))} |`);
  L.push('');
  if (c.meta.why) L.push(`**Why it retains:** ${c.meta.why}`, '');
  if (c.beats.length) {
    L.push('**Retention beats** (the editing decisions, in order)', '', '| t | beat |', '|---:|---|');
    for (const b of c.beats) L.push(`| ${b.t.toFixed(2)} s | ${md(b.label)} |`);
    L.push('');
  }
  L.push(`**Showcase card:** ${md(c.meta.niche)} · *${md(c.meta.title)}*${c.meta.facts ? `  \n**Facts:** ${md(c.meta.facts)}` : ''}`, '');
  L.push('**Examples**', '', '| params | niche | title | frame |', '|---|---|---|---|');
  L.push(`| defaults | ${md(c.meta.niche)} | ${md(c.meta.title)} | ${fs.existsSync(path.join(ROOT, 'styles', c.id, 'poster.jpg')) ? '<img src="poster.jpg" width="240">' : '—'} |`);
  for (const e of ex) L.push(`| [\`${e.file}\`](${e.file}) | ${md(e.meta.niche || '')} | ${md(e.meta.title || '')} | ${e.jpg ? `<img src="${e.jpg}" width="240">` : '—'} |`);
  L.push('');
  L.push('**Render**', '', '```bash');
  L.push(`node tools/render.mjs sheet ${c.id}`);
  if (ex[0]) L.push(`node tools/render.mjs video ${c.id} --params styles/${c.id}/${ex[0].file}`);
  else L.push(`node tools/render.mjs video ${c.id} --params my-params.json`);
  L.push('```', '');
  L.push('<details><summary>Default params (copy into a params file and change what you need)</summary>', '', '```json');
  L.push(pretty(c.defaults));
  L.push('```', '</details>');
  L.push('<!-- catalog:end -->');
  return L.join('\n');
}

function refreshReadme(c) {
  const file = path.join(ROOT, 'styles', c.id, 'README.md');
  if (!fs.existsSync(file)) { console.log(`  ${c.id}: no README.md (copy styles/_template/README.md)`); return; }
  const src = fs.readFileSync(file, 'utf8');
  const a = src.indexOf('<!-- catalog:start'), b = src.indexOf('<!-- catalog:end -->');
  if (a < 0 || b < 0) { console.log(`  ${c.id}: README.md has no catalog markers, skipped`); return; }
  fs.writeFileSync(file, src.slice(0, a) + block(c) + src.slice(b + '<!-- catalog:end -->'.length));
  console.log(`  ${c.id}: README block refreshed`);
}

function writeIndex(cat) {
  const L = ['# Styles', '',
    'Every style is a reusable, param-driven motion piece. Pick one by niche here or in',
    '[docs/NICHE-MAP.md](../docs/NICHE-MAP.md); each card has its params, examples and render commands.', '',
    '_Generated by `node tools/catalog.mjs`._', '',
    '| | style | primary niches | also fits | length | examples |', '|---|---|---|---|---:|---:|'];
  for (const c of cat) {
    const img = fs.existsSync(path.join(ROOT, 'styles', c.id, 'poster.jpg')) ? `<img src="${c.id}/poster.jpg" width="200">` : '';
    L.push(`| ${img} | **[${md(c.name)}](${c.id}/README.md)**<br>\`${c.id}\` | ${md(list(c.niches && c.niches.primary))} | ${md(list(c.niches && c.niches.similar))} | ${c.duration.toFixed(1)} s | ${examplesOf(c.id).length} |`);
  }
  fs.writeFileSync(path.join(ROOT, 'styles', 'README.md'), L.join('\n') + '\n');

  // niche -> styles
  const map = new Map();
  const labels = new Map();   // niche names match case-insensitively; the first spelling seen is shown
  const add = (n, c, rank) => { const k = n.trim().toLowerCase(); if (!map.has(k)) { map.set(k, []); labels.set(k, n.trim()); } map.get(k).push({ c, rank }); };
  for (const c of cat) {
    (c.niches?.primary || []).forEach((n) => add(n, c, 'primary'));
    (c.niches?.similar || []).forEach((n) => add(n, c, 'similar'));
    examplesOf(c.id).forEach((e) => e.meta.niche && add(e.meta.niche, c, 'example'));
  }
  const keys = [...map.keys()].sort((a, b) => a.localeCompare(b));
  const N = ['# Niche map', '',
    'Which style to reach for, by niche. **Bold** = built for it (primary), plain = adapts well (similar),',
    '_italic_ = an example params file already exists for it. Styles not listed for a niche can still work: read',
    'the style cards in [styles/README.md](../styles/README.md).', '',
    '_Generated by `node tools/catalog.mjs` from each style\'s `niches` and its `examples/*.json`._', '',
    '| niche | styles |', '|---|---|'];
  for (const k of keys) {
    const seen = new Map();
    for (const { c, rank } of map.get(k)) {
      const prev = seen.get(c.id);
      const order = { primary: 0, example: 1, similar: 2 };
      if (!prev || order[rank] < order[prev.rank]) seen.set(c.id, { c, rank });
    }
    const cells = [...seen.values()].sort((a, b) => ({ primary: 0, example: 1, similar: 2 }[a.rank] - { primary: 0, example: 1, similar: 2 }[b.rank]))
      .map(({ c, rank }) => { const l = `[${c.id}](../styles/${c.id}/README.md)`; return rank === 'primary' ? `**${l}**` : rank === 'example' ? `_${l}_` : l; });
    N.push(`| ${md(labels.get(k))} | ${cells.join(' · ')} |`);
  }
  N.push('', '## By style', '');
  for (const c of cat) N.push(`- **[${md(c.name)}](../styles/${c.id}/README.md)** \`${c.id}\`: ${md(list(c.niches?.primary))}; also ${md(list(c.niches?.similar))}`);
  fs.writeFileSync(path.join(ROOT, 'docs', 'NICHE-MAP.md'), N.join('\n') + '\n');
  console.log(`  styles/README.md + docs/NICHE-MAP.md (${keys.length} niches)`);
}

const ids = pos.length ? pos : all;
const cat = (await readCatalog(ids)).sort((a, b) => (a.order ?? 99) - (b.order ?? 99) || a.id.localeCompare(b.id));
if (flags.json) { console.log(JSON.stringify(cat, null, 2)); process.exit(0); }
for (const c of cat) refreshReadme(c);
if (!pos.length) writeIndex(cat);
