#!/usr/bin/env node
// Builds data/mapdata.js from data/maps.config.json: Natural Earth (world-atlas 50m) land projected with
// Mercator into a 1920x1080 frame per region. In a style: const M = MAPDATA[key], P = Reel.mercator(M.k, M.tx, M.ty).
//
// Region config:
//   bounds [[lonW, latS], [lonE, latN]]  area that must fit the frame     pad   inset in px
//   clip   px of land kept beyond the frame (room for camera moves)        borders  true = country borders mesh
//   countries { key: "ISO numeric id" }  extra per-country paths (e.g. "cuba": "192")
//   site { name, lon, lat } + cities [[name, lon, lat], ...]  cities get great-circle km/nm from the site
//   rings [{ label, nm }]  range rings (deg = nm / 60)
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { feature, mesh } from 'topojson-client';
import { geoMercator, geoPath, geoDistance } from 'd3-geo';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (f) => JSON.parse(fs.readFileSync(path.join(ROOT, 'node_modules', 'world-atlas', f), 'utf8'));
const land50 = read('land-50m.json'), c50 = read('countries-50m.json');
const land = feature(land50, land50.objects.land);
const countries = feature(c50, c50.objects.countries);
const bordersMesh = mesh(c50, c50.objects.countries, (a, b) => a !== b);
const byId = (id) => countries.features.find((f) => String(f.id).padStart(3, '0') === String(id).padStart(3, '0'));
const config = JSON.parse(fs.readFileSync(path.join(ROOT, 'data', 'maps.config.json'), 'utf8'));

const data = {};
for (const [key, R] of Object.entries(config)) {
  const [[lon0, lat0], [lon1, lat1]] = R.bounds;
  const box = { type: 'MultiPoint', coordinates: [[lon0, lat0], [lon1, lat1], [lon0, lat1], [lon1, lat0]] };
  const pad = R.pad ?? 20, clip = R.clip ?? 600;
  const proj = geoMercator().fitExtent([[pad, pad], [1920 - pad, 1080 - pad]], box);
  proj.clipExtent([[-clip, -clip], [1920 + clip, 1080 + clip]]);
  const p = geoPath(proj).digits(1);
  const out = { k: +proj.scale().toFixed(6), tx: +proj.translate()[0].toFixed(4), ty: +proj.translate()[1].toFixed(4), land: p(land) };
  if (R.borders) out.borders = p(bordersMesh);
  for (const [name, id] of Object.entries(R.countries || {})) {
    const f = byId(id);
    if (!f) throw new Error(`${key}: no country with id ${id}`);
    out[name] = p(f);
  }
  if (R.site) {
    const S = [R.site.lon, R.site.lat];
    out.site = { name: R.site.name, lon: S[0], lat: S[1], x: +proj(S)[0].toFixed(1), y: +proj(S)[1].toFixed(1) };
    if (R.rings) out.rings = R.rings.map((r) => ({ label: r.label, nm: r.nm, deg: r.nm / 60 }));
    if (R.cities) {
      out.cities = R.cities.map(([name, lon, lat]) => {
        const km = geoDistance(S, [lon, lat]) * 6371.0088;
        return { name, lon, lat, km: Math.round(km), nm: Math.round(km / 1.852), x: +proj([lon, lat])[0].toFixed(1), y: +proj([lon, lat])[1].toFixed(1) };
      }).sort((a, b) => a.km - b.km);
    }
  } else if (R.cities) {
    out.cities = R.cities.map(([name, lon, lat]) => ({ name, lon, lat, x: +proj([lon, lat])[0].toFixed(1), y: +proj([lon, lat])[1].toFixed(1) }));
  }
  data[key] = out;
  console.log(`${key.padEnd(12)} k=${out.k} land ${(out.land.length / 1024).toFixed(0)} KB${out.cities ? ` · ${out.cities.length} cities` : ''}`);
}
const js = `/* Generated by tools/mapgen.mjs from data/maps.config.json (Natural Earth, world-atlas 50m). Mercator, 1920x1080 frame. */\nwindow.MAPDATA = ${JSON.stringify(data)};\n`;
fs.writeFileSync(path.join(ROOT, 'data', 'mapdata.js'), js);
console.log(`data/mapdata.js ${(js.length / 1024).toFixed(0)} KB`);
