#!/usr/bin/env node
/*
  Publish the rendered videos as downloads on a GitHub Release (they are too big for git).

  node tools/release.mjs              list what would ship and write showcase/release-assets.json (the website reads it)
  node tools/release.mjs --upload     also create the release v<package.json version> and upload every file (gh CLI)

  Every reel in reels/ with renders in showcase/<slug>/ contributes its full reel, 720p share copy, pieces and
  transparent overlays, named <fileBase>-… so names never collide. Re-running --upload replaces files of the same
  name. Needs the GitHub CLI signed in (gh auth login) and package.json "repository" pointing at the repo.
*/
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { ROOT, listReels, resolveTarget, releaseAssets, repoInfo, parseArgs } from './lib.mjs';

const { flags } = parseArgs(process.argv.slice(2));
const info = repoInfo();
const assets = [], reels = [];
for (const file of listReels()) {
  const reel = resolveTarget(file);
  const a = releaseAssets(reel);
  if (!a.length) continue;
  reels.push({ slug: reel.slug, name: reel.name });
  assets.push(...a);
}
const mb = (b) => (b / 1e6).toFixed(1) + ' MB';
for (const a of assets) console.log(`${a.kind.padEnd(6)} ${a.name.padEnd(58)} ${mb(a.size).padStart(9)}`);
console.log(`${assets.length} files · ${mb(assets.reduce((s, a) => s + a.size, 0))} → ${info.url}/releases/tag/${info.tag}`);

const manifest = {
  tag: info.tag, repo: info.url,
  note: 'Generated by tools/release.mjs. The website (tools/build-site.mjs) links these release downloads.',
  assets: assets.map(({ reel, kind, name, size, key, n }) => ({ reel, kind, name, size, ...(key ? { key } : {}), ...(n ? { n } : {}) })),
};
fs.writeFileSync(path.join(ROOT, 'showcase', 'release-assets.json'), JSON.stringify(manifest, null, 2) + '\n');
console.log('wrote showcase/release-assets.json');

if (!flags.upload) process.exit(0);
if (!info.owner) throw new Error('package.json "repository.url" must point at a GitHub repo');
const gh = (args, opts = {}) => spawnSync('gh', args, { cwd: ROOT, encoding: 'utf8', ...opts });
const repo = `${info.owner}/${info.repo}`;
if (gh(['release', 'view', info.tag, '--repo', repo]).status !== 0) {
  const notes = [
    `Rendered deliverables for Motion Reel Kit ${info.tag}. Everything here is generated from the code in this repo; re-render any file with \`node tools/export-reel.mjs reels/<reel>.json\`.`,
    '', ...reels.map((r) => `- **${r.name}**: full reel (1080p60 and 720p), every piece on its own${assets.some((a) => a.reel === r.slug && a.kind === 'alpha') ? ', transparent ProRes 4444 overlay' : ''}`),
    '', info.homepage ? `Watch the reels live and browse the styles: ${info.homepage}` : '',
  ].join('\n');
  const r = gh(['release', 'create', info.tag, '--repo', repo, '--title', `Motion Reel Kit ${info.tag}`, '--notes', notes], { stdio: 'inherit' });
  if (r.status !== 0) throw new Error('gh release create failed');
}
// stage copies under their release names, then upload one by one (progress stays visible)
const stage = path.join(ROOT, 'build', 'release', info.tag);
fs.mkdirSync(stage, { recursive: true });
for (const [i, a] of assets.entries()) {
  const staged = path.join(stage, a.name);
  if (!fs.existsSync(staged) || fs.statSync(staged).size !== a.size) fs.copyFileSync(a.local, staged);
  process.stdout.write(`[${i + 1}/${assets.length}] ${a.name} (${mb(a.size)}) … `);
  const r = gh(['release', 'upload', info.tag, staged, '--repo', repo, '--clobber']);
  console.log(r.status === 0 ? 'done' : `FAILED\n${r.stderr}`);
  if (r.status !== 0) process.exitCode = 1;
}
fs.rmSync(stage, { recursive: true, force: true });
console.log(`release: ${info.url}/releases/tag/${info.tag}`);
